# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iia0I7CpzmVKSgAfmVNi5S9alvznWziY
"""

import numpy as np 
import pandas as pd 
import scipy.stats as stats

"""Step 1: we use to import libraries
Step 2: add modules 
Step 3: Create an arry of values
"""

data = np.array([6,7,7,12,13,13,16,19,5,11])

"""Step 4: Calculate the z_scores for each value in array."""

stats.zscore(data)

"""Zscore show us the standard deviation of a number from the calculated mean."""



